name: Tests

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: codecov/codecov-action@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '16'
        - run: npm ci
        - run: npm test
        - name: Codecov
          uses: codecov/codecov-action@v1
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            flags: unittests
